#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ammeter
Version  : 1.1.4
Release  : 9
URL      : https://rubygems.org/downloads/ammeter-1.1.4.gem
Source0  : https://rubygems.org/downloads/ammeter-1.1.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-actionpack
BuildRequires : rubygem-actionview
BuildRequires : rubygem-activerecord
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-aruba
BuildRequires : rubygem-builder
BuildRequires : rubygem-bundler
BuildRequires : rubygem-coffee-rails
BuildRequires : rubygem-cucumber
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-erubis
BuildRequires : rubygem-haml-rails
BuildRequires : rubygem-i18n
BuildRequires : rubygem-jquery-rails
BuildRequires : rubygem-loofah
BuildRequires : rubygem-mini_portile
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rack
BuildRequires : rubygem-rack-test
BuildRequires : rubygem-rails
BuildRequires : rubygem-rails-deprecated_sanitizer
BuildRequires : rubygem-rails-dom-testing
BuildRequires : rubygem-rails-html-sanitizer
BuildRequires : rubygem-railties
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-rails
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-sass-rails
BuildRequires : rubygem-sqlite3
BuildRequires : rubygem-thor
BuildRequires : rubygem-thread_safe
BuildRequires : rubygem-tzinfo
BuildRequires : rubygem-uglifier

%description
# Ammeter [![Build Status](https://secure.travis-ci.org/alexrothenberg/ammeter.png)](http://travis-ci.org/alexrothenberg/ammeter) [![Code Climate](https://codeclimate.com/github/alexrothenberg/ammeter.png)](https://codeclimate.com/github/alexrothenberg/ammeter) [![Gem Version](https://badge.fury.io/rb/ammeter.png)](http://badge.fury.io/rb/ammeter)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ammeter-1.1.4
gem spec %{SOURCE0} -l --ruby > rubygem-ammeter.gemspec

%build
export LANG=C
gem build rubygem-ammeter.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ammeter-1.1.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ammeter-1.1.4.gem
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/History.md
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/README.md
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/ammeter.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/generator_in_a_gem.feature
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/generator_spec.feature
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/generator_with_shell_prompts_spec.feature
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/hooking_into_other_generators.feature
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/support/aruba_timeout.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/templates/generate_example_app.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/templates/my_rails_gem/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/templates/my_rails_gem/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/templates/my_rails_gem/my_rails_gem.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/templates/my_rails_gem/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/templates/my_railties_gem/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/templates/my_railties_gem/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/templates/my_railties_gem/my_railties_gem.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/templates/my_railties_gem/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/features/templates/rspec.rake
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/init.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/output_capturer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/rspec/generator/example.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/rspec/generator/example/generator_example_group.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/rspec/generator/example/generator_example_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/rspec/generator/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/rspec/generator/matchers/be_a_migration.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/rspec/generator/matchers/contain.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/rspec/generator/matchers/exist.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/rspec/generator/matchers/have_correct_syntax.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/rspec/generator/matchers/have_method.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/rspec/rspec_2_compatibility.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/lib/ammeter/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/ammeter/rspec/generator/example/generator_example_group_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/ammeter/rspec/generator/example/generator_example_helpers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/ammeter/rspec/generator/matchers/be_a_migration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/ammeter/rspec/generator/matchers/contain_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/ammeter/rspec/generator/matchers/exist_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/ammeter/rspec/generator/matchers/have_correct_syntax_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/ammeter/rspec/generator/matchers/have_method_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/support/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/support/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/support/memoized_helpers_rspec2compatibility.rb
/usr/lib64/ruby/gems/2.3.0/gems/ammeter-1.1.4/spec/support/mock_generator.rb
/usr/lib64/ruby/gems/2.3.0/specifications/ammeter-1.1.4.gemspec
